//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_Course_Work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursion
    {
        public Excursion()
        {
            this.Tur = new HashSet<Tur>();
        }
    
        public int ExcursionID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Length { get; set; }
        public string Time { get; set; }
        public double Cost { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Tur> Tur { get; set; }
    }
}
