//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_Course_Work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int HotelID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rating { get; set; }
        public double Cost { get; set; }
        public string Food { get; set; }
    }
}
