//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_Course_Work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tur
    {
        public Tur()
        {
            this.Excursion = new HashSet<Excursion>();
        }
    
        public int TurID { get; set; }
        public string Country { get; set; }
        public System.DateTime DateO { get; set; }
        public System.DateTime DateI { get; set; }
        public string Day_Night { get; set; }
        public double Cost { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Excursion> Excursion { get; set; }
    }
}
